# ===============================
# SERVER CONFIG
# ===============================
server.port=8082
spring.application.name=JOB-SERVICE

#================================
# ENV SUPPORT
#===============================
spring.config.import=optional:file:.env[.properties]

# ===============================
# DATABASE CONFIG (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/jobdb?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

## ===============================
## LOGGING (VERY USEFUL)
## ===============================
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# SWAGGER / OPENAPI
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html


# ==============================
# EUREKA CONFIG
# ==============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# ================================
# RABBIT MQ CONFIG
# ================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASS}



# ZEPKINS CONFIG
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans


#REDIS CONFIG
spring.data.redis.host=localhost
spring.data.redis.port=6379


# ======================
# ACTUATOR CONFIG
# ======================
management.endpoints.web.exposure.include=health,info,prometheus

# ======================
# PROMETHEUS METRICS
# ======================
management.prometheus.metrics.export.enabled=true

# ======================
# HEALTH DETAILS
# ======================
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}