spring.application.name=Notification-Service

# ===============================
# SERVER CONFIG
# ===============================
server.port=8085


#ENV CONFIG
spring.config.import=optional:file:.env[.properties]

# ===============================
# RABBITMQ CONFIG
# ===============================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASS}


# ===============================
# EMAIL CONFIG (GMAIL SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# ===============================
# OPTIONAL (DEBUGGING)
# ===============================
logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.mail=DEBUG


# ZEPKINS CONFIG
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans


# ======================
# ACTUATOR CONFIG
# ======================
management.endpoints.web.exposure.include=health,info,prometheus

# ======================
# PROMETHEUS METRICS
# ======================
management.prometheus.metrics.export.enabled=true

# ======================
# HEALTH DETAILS
# ======================
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
