# Server
server.port=8080

# App name
spring.application.name=API-GATEWAY

#ENV CONFIG
spring.config.import=optional:file:.env[.properties]

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true


# JOB SERVICE
spring.cloud.gateway.server.webflux.routes[0].id=job-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://JOB-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/jobs/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=JwtAuthenticationFilter

# AUTH SERVICE (NO FILTER)
spring.cloud.gateway.server.webflux.routes[1].id=auth-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/auth/**

#USER SERVICE
spring.cloud.gateway.server.webflux.routes[4].id=auth-user-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/user/**
spring.cloud.gateway.server.webflux.routes[4].filters[0]=JwtAuthenticationFilter


## APPLICATION SERVICE
spring.cloud.gateway.server.webflux.routes[2].id=application-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://APPLICATION-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/applications/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=JwtAuthenticationFilter

## ADMIN SERVICE
spring.cloud.gateway.server.webflux.routes[3].id=admin-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://ADMIN-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/admin/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=JwtAuthenticationFilter

jwt.secret=${JWT_SECRET}

# LOGGING
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG


# ZEPKINS CONFIG
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans


# ======================
# ACTUATOR CONFIG
# ======================
management.endpoints.web.exposure.include=health,info,prometheus

# ======================
# PROMETHEUS METRICS
# ======================
management.prometheus.metrics.export.enabled=true

# ======================
# HEALTH DETAILS
# ======================
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}