server.port=8084
spring.application.name=ADMIN-SERVICE

# =======================
# EUREKA CONFIG
# ========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# =======================
# FEIGN TIMEOUT SETTINGS
# =======================
spring.cloud.openfeign.client.config.default.connectTimeout=2000
spring.cloud.openfeign.client.config.default.readTimeout=4000

# =======================
# RESILIENCE4J - JOB SERVICE
# =======================
resilience4j.circuitbreaker.instances.jobService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.jobService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.jobService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.jobService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.jobService.waitDurationInOpenState=20s
resilience4j.circuitbreaker.instances.jobService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.jobService.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.jobService.ignoreExceptions=com.capg.AdminService.exception.UnauthorizedException,java.lang.IllegalStateException


# =======================
# RESILIENCE4J - USER/AUTH SERVICE
# =======================
resilience4j.circuitbreaker.instances.authService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.authService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.authService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.authService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.authService.waitDurationInOpenState=20s
resilience4j.circuitbreaker.instances.authService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.authService.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.authService.ignoreExceptions=com.capg.AdminService.exception.UnauthorizedException


# =======================
# RESILIENCE4J - APPLICATION SERVICE
# =======================
resilience4j.circuitbreaker.instances.applicationService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.applicationService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.applicationService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.applicationService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.applicationService.waitDurationInOpenState=20s
resilience4j.circuitbreaker.instances.applicationService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.applicationService.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.applicationService.ignoreExceptions=com.capg.AdminService.exception.UnauthorizedException


# ZEPKINS CONFIG
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans



# ======================
# ACTUATOR CONFIG
# ======================
management.endpoints.web.exposure.include=health,info,prometheus

# ======================
# PROMETHEUS METRICS
# ======================
management.prometheus.metrics.export.enabled=true

# ======================
# HEALTH DETAILS
# ======================
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}